/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CafesRouteImport } from './routes/cafes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForCafesRouteImport } from './routes/for-cafes'
import { Route as ForRestaurantsRouteImport } from './routes/for-restaurants'
import { Route as GameRouteImport } from './routes/game'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminGameSupportRouteImport } from './routes/admin.game-support'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as BusinessBusinessIdRouteImport } from './routes/business.$businessId'
import { Route as BusinessesIndexRouteImport } from './routes/businesses.index'
import { Route as BusinessesBusinessIdRouteImport } from './routes/businesses.$businessId'
import { Route as CafeDashboardRouteImport } from './routes/cafe.dashboard'
import { Route as CafeGameSupportRouteImport } from './routes/cafe.game-support'
import { Route as CafeLoginRouteImport } from './routes/cafe.login'
import { Route as CafeOrdersRouteImport } from './routes/cafe.orders'
import { Route as CafeRegisterRouteImport } from './routes/cafe.register'
import { Route as CustomerCafesRouteImport } from './routes/customer.cafes'
import { Route as CustomerCartRouteImport } from './routes/customer.cart'
import { Route as CustomerCheckoutRouteImport } from './routes/customer.checkout'
import { Route as CustomerGameSupportRouteImport } from './routes/customer.game-support'
import { Route as CustomerRestaurantsRouteImport } from './routes/customer.restaurants'
import { Route as OrderTokenRouteImport } from './routes/order.$token'
import { Route as RestaurantDashboardRouteImport } from './routes/restaurant.dashboard'
import { Route as RestaurantGameSupportRouteImport } from './routes/restaurant.game-support'
import { Route as RestaurantLoginRouteImport } from './routes/restaurant.login'
import { Route as RestaurantOrdersRouteImport } from './routes/restaurant.orders'
import { Route as RestaurantRegisterRouteImport } from './routes/restaurant.register'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin.dashboard.index'
import { Route as AdminDashboardSectionRouteImport } from './routes/admin.dashboard.$section'
import { Route as ApiPublicSyncBusinessesRouteImport } from './routes/api/public/sync-businesses'
import { Route as CafeDashboardIndexRouteImport } from './routes/cafe.dashboard.index'
import { Route as CafeDashboardSectionRouteImport } from './routes/cafe.dashboard.$section'
import { Route as CustomerOrdersIndexRouteImport } from './routes/customer.orders.index'
import { Route as CustomerOrdersOrderIdRouteImport } from './routes/customer.orders.$orderId'
import { Route as RestaurantDashboardIndexRouteImport } from './routes/restaurant.dashboard.index'
import { Route as RestaurantDashboardSectionRouteImport } from './routes/restaurant.dashboard.$section'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CafesRoute = CafesRouteImport.update({
  id: '/cafes',
  path: '/cafes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCafesRoute = ForCafesRouteImport.update({
  id: '/for-cafes',
  path: '/for-cafes',
  getParentRoute: () => rootRouteImport,
} as any)
const ForRestaurantsRoute = ForRestaurantsRouteImport.update({
  id: '/for-restaurants',
  path: '/for-restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGameSupportRoute = AdminGameSupportRouteImport.update({
  id: '/admin/game-support',
  path: '/admin/game-support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessBusinessIdRoute = BusinessBusinessIdRouteImport.update({
  id: '/business/$businessId',
  path: '/business/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesBusinessIdRoute = BusinessesBusinessIdRouteImport.update({
  id: '/businesses/$businessId',
  path: '/businesses/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeDashboardRoute = CafeDashboardRouteImport.update({
  id: '/cafe/dashboard',
  path: '/cafe/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeGameSupportRoute = CafeGameSupportRouteImport.update({
  id: '/cafe/game-support',
  path: '/cafe/game-support',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeLoginRoute = CafeLoginRouteImport.update({
  id: '/cafe/login',
  path: '/cafe/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeOrdersRoute = CafeOrdersRouteImport.update({
  id: '/cafe/orders',
  path: '/cafe/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeRegisterRoute = CafeRegisterRouteImport.update({
  id: '/cafe/register',
  path: '/cafe/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCafesRoute = CustomerCafesRouteImport.update({
  id: '/customer/cafes',
  path: '/customer/cafes',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/customer/cart',
  path: '/customer/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: '/customer/checkout',
  path: '/customer/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerGameSupportRoute = CustomerGameSupportRouteImport.update({
  id: '/customer/game-support',
  path: '/customer/game-support',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRestaurantsRoute = CustomerRestaurantsRouteImport.update({
  id: '/customer/restaurants',
  path: '/customer/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTokenRoute = OrderTokenRouteImport.update({
  id: '/order/$token',
  path: '/order/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantDashboardRoute = RestaurantDashboardRouteImport.update({
  id: '/restaurant/dashboard',
  path: '/restaurant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantGameSupportRoute = RestaurantGameSupportRouteImport.update({
  id: '/restaurant/game-support',
  path: '/restaurant/game-support',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantLoginRoute = RestaurantLoginRouteImport.update({
  id: '/restaurant/login',
  path: '/restaurant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantOrdersRoute = RestaurantOrdersRouteImport.update({
  id: '/restaurant/orders',
  path: '/restaurant/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRegisterRoute = RestaurantRegisterRouteImport.update({
  id: '/restaurant/register',
  path: '/restaurant/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardSectionRoute = AdminDashboardSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const ApiPublicSyncBusinessesRoute = ApiPublicSyncBusinessesRouteImport.update({
  id: '/api/public/sync-businesses',
  path: '/api/public/sync-businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeDashboardIndexRoute = CafeDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CafeDashboardRoute,
} as any)
const CafeDashboardSectionRoute = CafeDashboardSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => CafeDashboardRoute,
} as any)
const CustomerOrdersIndexRoute = CustomerOrdersIndexRouteImport.update({
  id: '/customer/orders/',
  path: '/customer/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersOrderIdRoute = CustomerOrdersOrderIdRouteImport.update({
  id: '/customer/orders/$orderId',
  path: '/customer/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantDashboardIndexRoute =
  RestaurantDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const RestaurantDashboardSectionRoute =
  RestaurantDashboardSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => RestaurantDashboardRoute,
  } as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cafes': typeof CafesRoute
  '/contact': typeof ContactRoute
  '/for-cafes': typeof ForCafesRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/game': typeof GameRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/restaurants': typeof RestaurantsRoute
  '/signup': typeof SignupRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/game-support': typeof AdminGameSupportRoute
  '/admin/login': typeof AdminLoginRoute
  '/business/$businessId': typeof BusinessBusinessIdRoute
  '/businesses/$businessId': typeof BusinessesBusinessIdRoute
  '/cafe/dashboard': typeof CafeDashboardRouteWithChildren
  '/cafe/game-support': typeof CafeGameSupportRoute
  '/cafe/login': typeof CafeLoginRoute
  '/cafe/orders': typeof CafeOrdersRoute
  '/cafe/register': typeof CafeRegisterRoute
  '/customer/cafes': typeof CustomerCafesRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/game-support': typeof CustomerGameSupportRoute
  '/customer/restaurants': typeof CustomerRestaurantsRoute
  '/order/$token': typeof OrderTokenRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRouteWithChildren
  '/restaurant/game-support': typeof RestaurantGameSupportRoute
  '/restaurant/login': typeof RestaurantLoginRoute
  '/restaurant/orders': typeof RestaurantOrdersRoute
  '/restaurant/register': typeof RestaurantRegisterRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/admin/dashboard/$section': typeof AdminDashboardSectionRoute
  '/api/public/sync-businesses': typeof ApiPublicSyncBusinessesRoute
  '/cafe/dashboard/$section': typeof CafeDashboardSectionRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/restaurant/dashboard/$section': typeof RestaurantDashboardSectionRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/cafe/dashboard/': typeof CafeDashboardIndexRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
  '/restaurant/dashboard/': typeof RestaurantDashboardIndexRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cafes': typeof CafesRoute
  '/contact': typeof ContactRoute
  '/for-cafes': typeof ForCafesRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/game': typeof GameRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/restaurants': typeof RestaurantsRoute
  '/signup': typeof SignupRoute
  '/admin/game-support': typeof AdminGameSupportRoute
  '/admin/login': typeof AdminLoginRoute
  '/business/$businessId': typeof BusinessBusinessIdRoute
  '/businesses/$businessId': typeof BusinessesBusinessIdRoute
  '/cafe/game-support': typeof CafeGameSupportRoute
  '/cafe/login': typeof CafeLoginRoute
  '/cafe/orders': typeof CafeOrdersRoute
  '/cafe/register': typeof CafeRegisterRoute
  '/customer/cafes': typeof CustomerCafesRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/game-support': typeof CustomerGameSupportRoute
  '/customer/restaurants': typeof CustomerRestaurantsRoute
  '/order/$token': typeof OrderTokenRoute
  '/restaurant/game-support': typeof RestaurantGameSupportRoute
  '/restaurant/login': typeof RestaurantLoginRoute
  '/restaurant/orders': typeof RestaurantOrdersRoute
  '/restaurant/register': typeof RestaurantRegisterRoute
  '/businesses': typeof BusinessesIndexRoute
  '/admin/dashboard/$section': typeof AdminDashboardSectionRoute
  '/api/public/sync-businesses': typeof ApiPublicSyncBusinessesRoute
  '/cafe/dashboard/$section': typeof CafeDashboardSectionRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/restaurant/dashboard/$section': typeof RestaurantDashboardSectionRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/cafe/dashboard': typeof CafeDashboardIndexRoute
  '/customer/orders': typeof CustomerOrdersIndexRoute
  '/restaurant/dashboard': typeof RestaurantDashboardIndexRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cafes': typeof CafesRoute
  '/contact': typeof ContactRoute
  '/for-cafes': typeof ForCafesRoute
  '/for-restaurants': typeof ForRestaurantsRoute
  '/game': typeof GameRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/restaurants': typeof RestaurantsRoute
  '/signup': typeof SignupRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/game-support': typeof AdminGameSupportRoute
  '/admin/login': typeof AdminLoginRoute
  '/business/$businessId': typeof BusinessBusinessIdRoute
  '/businesses/$businessId': typeof BusinessesBusinessIdRoute
  '/cafe/dashboard': typeof CafeDashboardRouteWithChildren
  '/cafe/game-support': typeof CafeGameSupportRoute
  '/cafe/login': typeof CafeLoginRoute
  '/cafe/orders': typeof CafeOrdersRoute
  '/cafe/register': typeof CafeRegisterRoute
  '/customer/cafes': typeof CustomerCafesRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRoute
  '/customer/game-support': typeof CustomerGameSupportRoute
  '/customer/restaurants': typeof CustomerRestaurantsRoute
  '/order/$token': typeof OrderTokenRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRouteWithChildren
  '/restaurant/game-support': typeof RestaurantGameSupportRoute
  '/restaurant/login': typeof RestaurantLoginRoute
  '/restaurant/orders': typeof RestaurantOrdersRoute
  '/restaurant/register': typeof RestaurantRegisterRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/admin/dashboard/$section': typeof AdminDashboardSectionRoute
  '/api/public/sync-businesses': typeof ApiPublicSyncBusinessesRoute
  '/cafe/dashboard/$section': typeof CafeDashboardSectionRoute
  '/customer/orders/$orderId': typeof CustomerOrdersOrderIdRoute
  '/restaurant/dashboard/$section': typeof RestaurantDashboardSectionRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/cafe/dashboard/': typeof CafeDashboardIndexRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
  '/restaurant/dashboard/': typeof RestaurantDashboardIndexRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cafes'
    | '/contact'
    | '/for-cafes'
    | '/for-restaurants'
    | '/game'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/profile'
    | '/restaurants'
    | '/signup'
    | '/admin/dashboard'
    | '/admin/game-support'
    | '/admin/login'
    | '/business/$businessId'
    | '/businesses/$businessId'
    | '/cafe/dashboard'
    | '/cafe/game-support'
    | '/cafe/login'
    | '/cafe/orders'
    | '/cafe/register'
    | '/customer/cafes'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/game-support'
    | '/customer/restaurants'
    | '/order/$token'
    | '/restaurant/dashboard'
    | '/restaurant/game-support'
    | '/restaurant/login'
    | '/restaurant/orders'
    | '/restaurant/register'
    | '/businesses/'
    | '/admin/dashboard/$section'
    | '/api/public/sync-businesses'
    | '/cafe/dashboard/$section'
    | '/customer/orders/$orderId'
    | '/restaurant/dashboard/$section'
    | '/admin/dashboard/'
    | '/cafe/dashboard/'
    | '/customer/orders/'
    | '/restaurant/dashboard/'
    | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cafes'
    | '/contact'
    | '/for-cafes'
    | '/for-restaurants'
    | '/game'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/profile'
    | '/restaurants'
    | '/signup'
    | '/admin/game-support'
    | '/admin/login'
    | '/business/$businessId'
    | '/businesses/$businessId'
    | '/cafe/game-support'
    | '/cafe/login'
    | '/cafe/orders'
    | '/cafe/register'
    | '/customer/cafes'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/game-support'
    | '/customer/restaurants'
    | '/order/$token'
    | '/restaurant/game-support'
    | '/restaurant/login'
    | '/restaurant/orders'
    | '/restaurant/register'
    | '/businesses'
    | '/admin/dashboard/$section'
    | '/api/public/sync-businesses'
    | '/cafe/dashboard/$section'
    | '/customer/orders/$orderId'
    | '/restaurant/dashboard/$section'
    | '/admin/dashboard'
    | '/cafe/dashboard'
    | '/customer/orders'
    | '/restaurant/dashboard'
    | '/api/public/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/cafes'
    | '/contact'
    | '/for-cafes'
    | '/for-restaurants'
    | '/game'
    | '/how-it-works'
    | '/login'
    | '/orders'
    | '/profile'
    | '/restaurants'
    | '/signup'
    | '/admin/dashboard'
    | '/admin/game-support'
    | '/admin/login'
    | '/business/$businessId'
    | '/businesses/$businessId'
    | '/cafe/dashboard'
    | '/cafe/game-support'
    | '/cafe/login'
    | '/cafe/orders'
    | '/cafe/register'
    | '/customer/cafes'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/game-support'
    | '/customer/restaurants'
    | '/order/$token'
    | '/restaurant/dashboard'
    | '/restaurant/game-support'
    | '/restaurant/login'
    | '/restaurant/orders'
    | '/restaurant/register'
    | '/businesses/'
    | '/admin/dashboard/$section'
    | '/api/public/sync-businesses'
    | '/cafe/dashboard/$section'
    | '/customer/orders/$orderId'
    | '/restaurant/dashboard/$section'
    | '/admin/dashboard/'
    | '/cafe/dashboard/'
    | '/customer/orders/'
    | '/restaurant/dashboard/'
    | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CafesRoute: typeof CafesRoute
  ContactRoute: typeof ContactRoute
  ForCafesRoute: typeof ForCafesRoute
  ForRestaurantsRoute: typeof ForRestaurantsRoute
  GameRoute: typeof GameRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  RestaurantsRoute: typeof RestaurantsRoute
  SignupRoute: typeof SignupRoute
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminGameSupportRoute: typeof AdminGameSupportRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BusinessBusinessIdRoute: typeof BusinessBusinessIdRoute
  BusinessesBusinessIdRoute: typeof BusinessesBusinessIdRoute
  CafeDashboardRoute: typeof CafeDashboardRouteWithChildren
  CafeGameSupportRoute: typeof CafeGameSupportRoute
  CafeLoginRoute: typeof CafeLoginRoute
  CafeOrdersRoute: typeof CafeOrdersRoute
  CafeRegisterRoute: typeof CafeRegisterRoute
  CustomerCafesRoute: typeof CustomerCafesRoute
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerCheckoutRoute: typeof CustomerCheckoutRoute
  CustomerGameSupportRoute: typeof CustomerGameSupportRoute
  CustomerRestaurantsRoute: typeof CustomerRestaurantsRoute
  OrderTokenRoute: typeof OrderTokenRoute
  RestaurantDashboardRoute: typeof RestaurantDashboardRouteWithChildren
  RestaurantGameSupportRoute: typeof RestaurantGameSupportRoute
  RestaurantLoginRoute: typeof RestaurantLoginRoute
  RestaurantOrdersRoute: typeof RestaurantOrdersRoute
  RestaurantRegisterRoute: typeof RestaurantRegisterRoute
  BusinessesIndexRoute: typeof BusinessesIndexRoute
  ApiPublicSyncBusinessesRoute: typeof ApiPublicSyncBusinessesRoute
  CustomerOrdersOrderIdRoute: typeof CustomerOrdersOrderIdRoute
  CustomerOrdersIndexRoute: typeof CustomerOrdersIndexRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafes': {
      id: '/cafes'
      path: '/cafes'
      fullPath: '/cafes'
      preLoaderRoute: typeof CafesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-cafes': {
      id: '/for-cafes'
      path: '/for-cafes'
      fullPath: '/for-cafes'
      preLoaderRoute: typeof ForCafesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-restaurants': {
      id: '/for-restaurants'
      path: '/for-restaurants'
      fullPath: '/for-restaurants'
      preLoaderRoute: typeof ForRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/game-support': {
      id: '/admin/game-support'
      path: '/admin/game-support'
      fullPath: '/admin/game-support'
      preLoaderRoute: typeof AdminGameSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$businessId': {
      id: '/business/$businessId'
      path: '/business/$businessId'
      fullPath: '/business/$businessId'
      preLoaderRoute: typeof BusinessBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$businessId': {
      id: '/businesses/$businessId'
      path: '/businesses/$businessId'
      fullPath: '/businesses/$businessId'
      preLoaderRoute: typeof BusinessesBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe/dashboard': {
      id: '/cafe/dashboard'
      path: '/cafe/dashboard'
      fullPath: '/cafe/dashboard'
      preLoaderRoute: typeof CafeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe/game-support': {
      id: '/cafe/game-support'
      path: '/cafe/game-support'
      fullPath: '/cafe/game-support'
      preLoaderRoute: typeof CafeGameSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe/login': {
      id: '/cafe/login'
      path: '/cafe/login'
      fullPath: '/cafe/login'
      preLoaderRoute: typeof CafeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe/orders': {
      id: '/cafe/orders'
      path: '/cafe/orders'
      fullPath: '/cafe/orders'
      preLoaderRoute: typeof CafeOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe/register': {
      id: '/cafe/register'
      path: '/cafe/register'
      fullPath: '/cafe/register'
      preLoaderRoute: typeof CafeRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/cafes': {
      id: '/customer/cafes'
      path: '/customer/cafes'
      fullPath: '/customer/cafes'
      preLoaderRoute: typeof CustomerCafesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/customer/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/checkout': {
      id: '/customer/checkout'
      path: '/customer/checkout'
      fullPath: '/customer/checkout'
      preLoaderRoute: typeof CustomerCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/game-support': {
      id: '/customer/game-support'
      path: '/customer/game-support'
      fullPath: '/customer/game-support'
      preLoaderRoute: typeof CustomerGameSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/restaurants': {
      id: '/customer/restaurants'
      path: '/customer/restaurants'
      fullPath: '/customer/restaurants'
      preLoaderRoute: typeof CustomerRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$token': {
      id: '/order/$token'
      path: '/order/$token'
      fullPath: '/order/$token'
      preLoaderRoute: typeof OrderTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/dashboard': {
      id: '/restaurant/dashboard'
      path: '/restaurant/dashboard'
      fullPath: '/restaurant/dashboard'
      preLoaderRoute: typeof RestaurantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/game-support': {
      id: '/restaurant/game-support'
      path: '/restaurant/game-support'
      fullPath: '/restaurant/game-support'
      preLoaderRoute: typeof RestaurantGameSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/login': {
      id: '/restaurant/login'
      path: '/restaurant/login'
      fullPath: '/restaurant/login'
      preLoaderRoute: typeof RestaurantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/orders': {
      id: '/restaurant/orders'
      path: '/restaurant/orders'
      fullPath: '/restaurant/orders'
      preLoaderRoute: typeof RestaurantOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/register': {
      id: '/restaurant/register'
      path: '/restaurant/register'
      fullPath: '/restaurant/register'
      preLoaderRoute: typeof RestaurantRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/$section': {
      id: '/admin/dashboard/$section'
      path: '/$section'
      fullPath: '/admin/dashboard/$section'
      preLoaderRoute: typeof AdminDashboardSectionRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/api/public/sync-businesses': {
      id: '/api/public/sync-businesses'
      path: '/api/public/sync-businesses'
      fullPath: '/api/public/sync-businesses'
      preLoaderRoute: typeof ApiPublicSyncBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe/dashboard/': {
      id: '/cafe/dashboard/'
      path: '/'
      fullPath: '/cafe/dashboard/'
      preLoaderRoute: typeof CafeDashboardIndexRouteImport
      parentRoute: typeof CafeDashboardRoute
    }
    '/cafe/dashboard/$section': {
      id: '/cafe/dashboard/$section'
      path: '/$section'
      fullPath: '/cafe/dashboard/$section'
      preLoaderRoute: typeof CafeDashboardSectionRouteImport
      parentRoute: typeof CafeDashboardRoute
    }
    '/customer/orders/': {
      id: '/customer/orders/'
      path: '/customer/orders'
      fullPath: '/customer/orders/'
      preLoaderRoute: typeof CustomerOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders/$orderId': {
      id: '/customer/orders/$orderId'
      path: '/customer/orders/$orderId'
      fullPath: '/customer/orders/$orderId'
      preLoaderRoute: typeof CustomerOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/dashboard/': {
      id: '/restaurant/dashboard/'
      path: '/'
      fullPath: '/restaurant/dashboard/'
      preLoaderRoute: typeof RestaurantDashboardIndexRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/restaurant/dashboard/$section': {
      id: '/restaurant/dashboard/$section'
      path: '/$section'
      fullPath: '/restaurant/dashboard/$section'
      preLoaderRoute: typeof RestaurantDashboardSectionRouteImport
      parentRoute: typeof RestaurantDashboardRoute
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardSectionRoute: typeof AdminDashboardSectionRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardSectionRoute: AdminDashboardSectionRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface CafeDashboardRouteChildren {
  CafeDashboardSectionRoute: typeof CafeDashboardSectionRoute
  CafeDashboardIndexRoute: typeof CafeDashboardIndexRoute
}

const CafeDashboardRouteChildren: CafeDashboardRouteChildren = {
  CafeDashboardSectionRoute: CafeDashboardSectionRoute,
  CafeDashboardIndexRoute: CafeDashboardIndexRoute,
}

const CafeDashboardRouteWithChildren = CafeDashboardRoute._addFileChildren(
  CafeDashboardRouteChildren,
)

interface RestaurantDashboardRouteChildren {
  RestaurantDashboardSectionRoute: typeof RestaurantDashboardSectionRoute
  RestaurantDashboardIndexRoute: typeof RestaurantDashboardIndexRoute
}

const RestaurantDashboardRouteChildren: RestaurantDashboardRouteChildren = {
  RestaurantDashboardSectionRoute: RestaurantDashboardSectionRoute,
  RestaurantDashboardIndexRoute: RestaurantDashboardIndexRoute,
}

const RestaurantDashboardRouteWithChildren =
  RestaurantDashboardRoute._addFileChildren(RestaurantDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CafesRoute: CafesRoute,
  ContactRoute: ContactRoute,
  ForCafesRoute: ForCafesRoute,
  ForRestaurantsRoute: ForRestaurantsRoute,
  GameRoute: GameRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  RestaurantsRoute: RestaurantsRoute,
  SignupRoute: SignupRoute,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminGameSupportRoute: AdminGameSupportRoute,
  AdminLoginRoute: AdminLoginRoute,
  BusinessBusinessIdRoute: BusinessBusinessIdRoute,
  BusinessesBusinessIdRoute: BusinessesBusinessIdRoute,
  CafeDashboardRoute: CafeDashboardRouteWithChildren,
  CafeGameSupportRoute: CafeGameSupportRoute,
  CafeLoginRoute: CafeLoginRoute,
  CafeOrdersRoute: CafeOrdersRoute,
  CafeRegisterRoute: CafeRegisterRoute,
  CustomerCafesRoute: CustomerCafesRoute,
  CustomerCartRoute: CustomerCartRoute,
  CustomerCheckoutRoute: CustomerCheckoutRoute,
  CustomerGameSupportRoute: CustomerGameSupportRoute,
  CustomerRestaurantsRoute: CustomerRestaurantsRoute,
  OrderTokenRoute: OrderTokenRoute,
  RestaurantDashboardRoute: RestaurantDashboardRouteWithChildren,
  RestaurantGameSupportRoute: RestaurantGameSupportRoute,
  RestaurantLoginRoute: RestaurantLoginRoute,
  RestaurantOrdersRoute: RestaurantOrdersRoute,
  RestaurantRegisterRoute: RestaurantRegisterRoute,
  BusinessesIndexRoute: BusinessesIndexRoute,
  ApiPublicSyncBusinessesRoute: ApiPublicSyncBusinessesRoute,
  CustomerOrdersOrderIdRoute: CustomerOrdersOrderIdRoute,
  CustomerOrdersIndexRoute: CustomerOrdersIndexRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
